# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rswag-specs/all/rswag-specs.rbi
#
# rswag-specs-2.4.0

module Rswag
end
module Rswag::Specs
  def self.config; end
end
module Rswag::Specs::ExampleGroupHelpers
  def consumes(*value); end
  def delete(summary, &block); end
  def deprecated(value); end
  def description(value = nil); end
  def examples(example = nil); end
  def get(summary, &block); end
  def head(summary, &block); end
  def header(name, attributes); end
  def operationId(value); end
  def options(summary, &block); end
  def parameter(attributes); end
  def patch(summary, &block); end
  def path(template, metadata = nil, &block); end
  def post(summary, &block); end
  def produces(*value); end
  def put(summary, &block); end
  def response(code, description, metadata = nil, &block); end
  def run_test!(&block); end
  def schema(value); end
  def schemes(*value); end
  def security(value); end
  def tags(*value); end
  def trace(summary, &block); end
end
class Rswag::Specs::RequestFactory
  def add_headers(request, metadata, swagger_doc, parameters, example); end
  def add_path(request, metadata, swagger_doc, parameters, example); end
  def add_payload(request, parameters, example); end
  def add_verb(request, metadata); end
  def build_form_payload(parameters, example); end
  def build_json_payload(parameters, example); end
  def build_query_string_part(param, value); end
  def build_request(metadata, example); end
  def definition_version(swagger_doc); end
  def derive_security_params(metadata, swagger_doc); end
  def doc_version(doc); end
  def expand_parameters(metadata, swagger_doc, example); end
  def initialize(config = nil); end
  def key_version(ref, swagger_doc); end
  def resolve_parameter(ref, swagger_doc); end
  def security_version(scheme_names, swagger_doc); end
end
class Rswag::Specs::ExtendedSchema < JSON::Schema::Draft4
  def initialize; end
end
class Rswag::Specs::ExtendedTypeAttribute < JSON::Schema::TypeV4Attribute
  def self.validate(current_schema, data, fragments, processor, validator, options = nil); end
end
class Rswag::Specs::ResponseValidator
  def definitions_or_component_schemas(swagger_doc, version); end
  def initialize(config = nil); end
  def validate!(metadata, response); end
  def validate_body!(metadata, swagger_doc, body); end
  def validate_code!(metadata, response); end
  def validate_headers!(metadata, headers); end
end
class Rswag::Specs::UnexpectedResponse < StandardError
end
module Rswag::Specs::ExampleHelpers
  def assert_response_matches_metadata(metadata); end
  def submit_request(metadata); end
end
class Rswag::Specs::Configuration
  def get_swagger_doc(name); end
  def get_swagger_doc_version(name); end
  def initialize(rspec_config); end
  def swagger_docs; end
  def swagger_dry_run; end
  def swagger_format; end
  def swagger_root; end
end
class Rswag::Specs::ConfigurationError < StandardError
end
class Rswag::Specs::Railtie < Rails::Railtie
end
module RSpec::Core::Configuration::Readers
  def swagger_docs; end
  def swagger_dry_run; end
  def swagger_format; end
  def swagger_root; end
end
