require:
  - rubocop-rspec

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Capybara/RSpec/PredicateMatcher:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  exclude_limit: example
