require:
  - rubocop-rspec

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-factory_bot
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/requests/tasker/**'
    - 'spec/swagger_helper.rb'

Style/Documentation:
  Enabled: false

# Factory-specific configurations to prevent aggressive code removal
Style/EmptyBlockParameter:
  Exclude:
    - 'spec/factories/**/*'

Style/ExplicitBlockArgument:
  Exclude:
    - 'spec/factories/**/*'

# Factories often have blocks that look "unused" but contain DSL attributes
Style/SymbolProc:
  Exclude:
    - 'spec/factories/**/*'

# Factory trait blocks often look redundant but define important variations
Style/RedundantBegin:
  Exclude:
    - 'spec/factories/**/*'

# Factory DSL often uses blocks that look like they could be simplified
Style/BlockDelimiters:
  Exclude:
    - 'spec/factories/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'spec/factories/**/*'  # Factories often have very long setup blocks
  Max: 120

Metrics/MethodLength:
  Max: 24

Metrics/ModuleLength:
  Max: 160

Metrics/ClassLength:
  Max: 140

Metrics/ParameterLists:
  Max: 8

Metrics/AbcSize:
  Max: 100

Naming/PredicateName:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

# Factory-specific RSpec exclusions
FactoryBot/CreateList:
  Exclude:
    - 'spec/factories/**/*'

# Factories often define many attributes that look like "excessive" setup
RSpec/ExcessiveDocstringSpacing:
  Exclude:
    - 'spec/factories/**/*'

# FactoryBot DSL uses 'context' for attributes, not RSpec example groups
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/factories/**/*'

RSpec/MissingExampleGroupArgument:
  Exclude:
    - 'spec/factories/**/*'

# Factory update_columns calls are intentional for test setup
Rails/SkipsModelValidations:
  Exclude:
    - 'spec/factories/**/*'
