require:
  - rubocop-rspec

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'
  Max: 120

Metrics/MethodLength:
  Max: 16

Capybara/RSpec/PredicateMatcher:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
  exclude_limit: example

Rspec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
