---
name: simple_dummy_task
module_namespace: Tasker
class_name: DummyTaskHandler
concurrent: true

default_dependent_system: test_system

named_steps:
  - step_one
  - step_two

schema:
  type: object
  required:
    - input_data
  properties:
    input_data:
      type: string

step_templates:
  - name: step_one
    description: First step
    handler_class: Tasker::StepHandler::Base
    default_retryable: true
    default_retry_limit: 3

  - name: step_two
    description: Second step
    depends_on_step: step_one
    handler_class: Tasker::StepHandler::Base
    default_retryable: true
    default_retry_limit: 3
