---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/tasker/tasks/{task_id}/task_diagram":
    parameters:
    - name: task_id
      in: path
      description: task_id
      required: true
      schema:
        type: integer
    get:
      summary: get task diagram
      tags:
      - Tasks
      description: Get Mermaid task diagram
      operationId: getTaskDiagram
      parameters:
      - name: format
        in: query
        required: false
        description: Response format (json, html)
        schema:
          type: string
      responses:
        '200':
          description: successful JSON response
          content:
            application/json:
              schema:
                type: object
                properties:
                  nodes:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        label:
                          type: string
                        shape:
                          type: string
                        style:
                          type: string
                        url:
                          type: string
                        attributes:
                          type: object
                  edges:
                    type: array
                    items:
                      type: object
                      properties:
                        source_id:
                          type: string
                        target_id:
                          type: string
                        label:
                          type: string
                        type:
                          type: string
                        direction:
                          type: string
                        attributes:
                          type: object
                  direction:
                    type: string
                  title:
                    type: string
                  attributes:
                    type: object
            text/html:
              schema:
                type: object
                properties:
                  nodes:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        label:
                          type: string
                        shape:
                          type: string
                        style:
                          type: string
                        url:
                          type: string
                        attributes:
                          type: object
                  edges:
                    type: array
                    items:
                      type: object
                      properties:
                        source_id:
                          type: string
                        target_id:
                          type: string
                        label:
                          type: string
                        type:
                          type: string
                        direction:
                          type: string
                        attributes:
                          type: object
                  direction:
                    type: string
                  title:
                    type: string
                  attributes:
                    type: object
        '404':
          description: task not found
  "/tasker/tasks":
    get:
      summary: list tasks
      tags:
      - Tasks
      description: Lists Tasks
      operationId: listTasks
      responses:
        '200':
          description: successful
    post:
      summary: create and enqueue task
      tags:
      - Tasks
      description: Create and Enqueue Task
      operationId: createTask
      parameters: []
      responses:
        '201':
          description: successful
        '400':
          description: bad request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                context:
                  type: object
                initiator:
                  type: string
                reason:
                  type: string
                source_system:
                  type: string
                tags:
                  type: array
                  items: string
              required:
              - name
              - context
  "/tasker/tasks/{task_id}":
    parameters:
    - name: task_id
      in: path
      description: task_id
      required: true
      schema:
        type: integer
    get:
      summary: show task
      tags:
      - Tasks
      description: Show Task
      operationId: getTask
      responses:
        '200':
          description: successful for completed task
    patch:
      summary: update task
      tags:
      - Tasks
      description: Update Task
      operationId: updateTask
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
                tags:
                  type: array
                  items: string
    put:
      summary: update task
      tags:
      - Tasks
      description: Update Task
      operationId: updateTask
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
                tags:
                  type: array
                  items: string
    delete:
      summary: cancel task
      tags:
      - Tasks
      description: Cancel Task
      operationId: cancelTask
      responses:
        '200':
          description: successful
  "/tasker/tasks/{task_id}/workflow_steps":
    parameters:
    - name: task_id
      in: path
      description: task_id
      required: true
      schema:
        type: string
    get:
      summary: list steps by task
      tags:
      - Steps
      description: List Steps by Task
      operationId: getStepsByTask
      responses:
        '200':
          description: successful
  "/tasker/tasks/{task_id}/workflow_steps/{step_id}":
    parameters:
    - name: task_id
      in: path
      description: task_id
      required: true
      schema:
        type: string
    - name: step_id
      in: path
      description: step_id
      required: true
      schema:
        type: string
    get:
      summary: show step by task
      tags:
      - Steps
      description: Show Step by Task
      operationId: getStepByTask
      responses:
        '200':
          description: successful
    patch:
      summary: update step by task
      tags:
      - Steps
      description: Update Step by Task
      operationId: updateStepByTask
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                retry_limit:
                  type: integer
                inputs:
                  type: object
    put:
      summary: update step by task
      tags:
      - Steps
      description: Update Step by Task
      operationId: updateStepByTask
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                retry_limit:
                  type: integer
                inputs:
                  type: object
    delete:
      summary: cancel step by task
      tags:
      - Steps
      description: Cancel Step by Task
      operationId: cancelStepByTask
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
